### ISSUE TITLE
[Menu] About

### ISSUE THREAD

**Issue by megax** [yeahunter/GrabTheMoment#15]
Lehetne leírás menüt csinálni. Lehetne trayicon-hoz is meg normális menüsorba. Itt le lehetne írni a program verzióját, rövid ismertetése stb.

**Comment by yeahunter** [comment]
Jelenleg vagy 20 alkalmazás van az értesítési területemen, ezek közül csak a Google Drive-nak van névjegy opciója ebben a formában. Így, a GTM-nek se kell ilyen funkció ebben a formában.

**Comment by megax** [comment]
Rendben. Akkor zárom a témát.
